'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
export type SocialPost={id:string;author_id:string;body:string;created_at:string;community_name:string;display_name:string;avatar_url?:string;verification?:string;reaction_count:number|string;comment_count:number|string;saved:boolean;my_reaction?:string|null};
type Comment={id:string;body:string;created_at:string;author_id:string;display_name:string;avatar_url?:string;verification?:string};
export default function SocialPostCard({post:initial}:{post:SocialPost}){ const[post,setPost]=useState(initial); const[comments,setComments]=useState<Comment[]>([]); const[showComments,setShowComments]=useState(false); const[message,setMessage]=useState(''); const avatarStyle=post.avatar_url?{backgroundImage:`url(${post.avatar_url})`}:undefined;
async function react(){const r=await fetch('/api/social/reactions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({postId:post.id,reaction:'respect'})});const j=await r.json();if(r.ok)setPost(v=>({...v,my_reaction:j.myReaction,reaction_count:j.reactionCount}));else setMessage(j.error||'Unable to react.');}
async function save(){const r=await fetch('/api/social/saves',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({postId:post.id})});const j=await r.json();if(r.ok)setPost(v=>({...v,saved:j.saved}));else setMessage(j.error||'Unable to save.');}
async function openComments(){const next=!showComments;setShowComments(next);if(next&&!comments.length){const r=await fetch(`/api/community/comments?postId=${encodeURIComponent(post.id)}`);const j=await r.json();if(r.ok)setComments(j.comments);}}
async function addComment(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const body=String(form.get('body')||'').trim();if(!body)return;const r=await fetch('/api/community/comments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({postId:post.id,body})});const j=await r.json();if(r.ok){e.currentTarget.reset();setPost(v=>({...v,comment_count:Number(v.comment_count||0)+1}));const rr=await fetch(`/api/community/comments?postId=${encodeURIComponent(post.id)}`);const jj=await rr.json();if(rr.ok)setComments(jj.comments);}else setMessage(j.error||'Unable to comment.');}
return <article className="panel socialPost"><div className="socialPostHead"><span className="miniAvatar" style={avatarStyle}>{post.display_name.slice(0,2).toUpperCase()}</span><div><Link href={`/members/${post.author_id}`}><b>{post.display_name}</b>{post.verification==='verified'&&<span className="verifiedBadge"> ✓</span>}</Link><small>{post.community_name} · {new Date(post.created_at).toLocaleString()}</small></div></div><div className="socialPostBody">{post.body}</div><div className="socialActions"><button className={post.my_reaction?'active':''} onClick={react}>⚓ Respect · {Number(post.reaction_count||0)}</button><button onClick={openComments}>💬 Reply · {Number(post.comment_count||0)}</button><button className={post.saved?'active':''} onClick={save}>🔖 {post.saved?'Saved':'Save'}</button></div>{message&&<small>{message}</small>}{showComments&&<div className="commentBox">{comments.map(c=><div className="commentRow" key={c.id}><div><Link href={`/members/${c.author_id}`}><b>{c.display_name}{c.verification==='verified'?' ✓':''}</b></Link><p>{c.body}</p><small>{new Date(c.created_at).toLocaleString()}</small></div></div>)}<form className="commentComposer" onSubmit={addComment}><input name="body" maxLength={5000} placeholder="Add a crew reply…" required/><button className="primaryButton small">Reply</button></form></div>}</article>; }
