'use client';
import { FormEvent,useEffect,useState } from 'react';
import AppShell from '@/components/AppShell';
import SocialPostCard,{SocialPost} from '@/components/SocialPostCard';
type Community={id:string;name:string;description?:string;department?:string;member_count:number;joined:boolean};
export default function CommunityPage(){const[communities,setCommunities]=useState<Community[]>([]),[active,setActive]=useState<Community|null>(null),[posts,setPosts]=useState<SocialPost[]>([]),[message,setMessage]=useState('');
async function loadCommunities(){const r=await fetch('/api/communities');const j=await r.json();if(r.ok){setCommunities(j.communities);setActive(c=>c?j.communities.find((x:Community)=>x.id===c.id)??c:j.communities[0]??null)}else setMessage(j.error||'Connect Neon and sign in to activate community data.');}
async function loadPosts(c?:Community|null){if(!c?.joined)return;const r=await fetch(`/api/community/posts?communityId=${encodeURIComponent(c.id)}`);const j=await r.json();if(r.ok)setPosts(j.posts);else setMessage(j.error||'Unable to load posts.');}
useEffect(()=>{let cancelled=false;void fetch('/api/communities').then(async r=>{const j=await r.json();if(cancelled)return;if(r.ok){setCommunities(j.communities);setActive(j.communities[0]??null)}else setMessage(j.error||'Connect Neon and sign in to activate community data.');});return()=>{cancelled=true};},[]);
const activeId=active?.id,activeJoined=active?.joined;useEffect(()=>{if(!activeId||!activeJoined)return;let cancelled=false;void fetch(`/api/community/posts?communityId=${encodeURIComponent(activeId)}`).then(async r=>{const j=await r.json();if(cancelled)return;if(r.ok)setPosts(j.posts);else setMessage(j.error||'Unable to load posts.');});return()=>{cancelled=true};},[activeId,activeJoined]);
async function toggleJoin(c:Community){const r=await fetch('/api/community/memberships',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({communityId:c.id,action:c.joined?'leave':'join'})});const j=await r.json();setMessage(r.ok?(c.joined?'Community left.':'Welcome aboard this community.'):j.error||'Unable to update membership.');if(r.ok){if(c.joined)setPosts([]);await loadCommunities();}}
async function post(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const body=String(new FormData(e.currentTarget).get('body')||'').trim();if(!body)return;const r=await fetch('/api/community/posts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({communityId:active.id,body})});const j=await r.json();if(r.ok){e.currentTarget.reset();setMessage('Post published.');await loadPosts(active)}else setMessage(j.error||'Unable to post.');}
return <AppShell title="Crew Community" kicker="PROFESSIONAL NETWORK"><div className="demoBanner">Department spaces, mentoring and real crew conversations. Social data becomes live after the Neon social migration is applied.</div>{message&&<p>{message}</p>}<div className="communityGrid">{communities.map((c,i)=><article className={`communityCard ${active?.id===c.id?'featuredPrice':''}`} key={c.id}><div className="communityIcon">{['⚓','◫','≈','⚙','✦'][i%5]}</div><span className="microLabel">{c.department||'CREW COMMUNITY'}</span><h3>{c.name}</h3><p>{c.description}</p><small>{c.member_count} members</small><div className="socialActions"><button onClick={()=>setActive(c)}>Open</button><button className={c.joined?'active':''} onClick={()=>toggleJoin(c)}>{c.joined?'Joined':'Join'}</button></div></article>)}</div>{active&&<><section className="panel"><div className="panelHead"><div><span className="microLabel">{active.joined?'MEMBER SPACE':'JOIN TO PARTICIPATE'}</span><h2>{active.name}</h2></div></div>{active.joined?<form className="supportForm" onSubmit={post}><label>Share with the crew<textarea name="body" rows={4} maxLength={10000} placeholder="Ask, answer, share experience or help another seafarer…" required/></label><button className="primaryButton">Publish post</button></form>:<p>Join this space to read and publish member posts.</p>}</section>{active.joined&&(posts.length?posts.map(p=><SocialPostCard key={p.id} post={p}/>):<section className="panel"><p>No posts yet. Start the conversation.</p></section>)}</>}</AppShell>;}
